# Generated by Django 5.1.6 on 2025-02-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='familias/'),
        ),
        migrations.AddField(
            model_name='perfilpersonal',
            name='genero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perfilpersonal',
            name='lengua_materna',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfilpersonal',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ActividadExtracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('terapia', 'Terapia'), ('deporte', 'Deporte'), ('arte', 'Arte'), ('taller', 'Taller')], max_length=10)),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(blank=True, max_length=50)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_extracurriculares', to='core.nino')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencias', models.TextField(blank=True)),
                ('aversiones', models.TextField(blank=True)),
                ('problemas_masticacion', models.BooleanField(default=False)),
                ('problemas_atragantamiento', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion', to='core.nino')),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentimiento_informado', models.BooleanField(default=False)),
                ('contacto_escuela', models.BooleanField(default=False)),
                ('proteccion_datos', models.BooleanField(default=False)),
                ('nino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacion', to='core.nino')),
            ],
        ),
        migrations.CreateModel(
            name='ControlEsfinteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_panales_diurno', models.BooleanField(default=False)),
                ('usa_panales_nocturno', models.BooleanField(default=False)),
                ('frecuencia_accidentes', models.CharField(blank=True, max_length=50)),
                ('senales_bano', models.TextField(blank=True)),
                ('miedo_inodoro', models.BooleanField(default=False)),
                ('estrategias', models.TextField(blank=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_esfinteres', to='core.nino')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geografia.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='nino',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direccion'),
        ),
        migrations.CreateModel(
            name='HitoDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hito', models.CharField(max_length=100)),
                ('edad_alcanzada', models.IntegerField(blank=True, null=True)),
                ('regresion', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_desarrollo', to='core.nino')),
            ],
        ),
        migrations.CreateModel(
            name='SensibilidadSensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('auditiva', 'Auditiva'), ('visual', 'Visual'), ('táctil', 'Táctil'), ('olfativa/gustativa', 'Olfativa/Gustativa')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensibilidades_sensoriales', to='core.nino')),
            ],
        ),
        migrations.CreateModel(
            name='Sueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_sueno_noche', models.IntegerField(blank=True, null=True)),
                ('siestas_diurnas', models.BooleanField(default=False)),
                ('dificultad_dormir', models.BooleanField(default=False)),
                ('despertares_nocturnos', models.BooleanField(default=False)),
                ('rutinas_previas', models.TextField(blank=True)),
                ('duerme_solo', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sueno', to='core.nino')),
            ],
        ),
    ]
